/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.project;

public class App {
  public String getGreeting() {
    return "Hello world222s";
  }

  public static void main(String[] args) {
    System.out.println("비가 옵니다. 천둥이 칩니다. 번개도 칩니다.");
  }
}
